const { Client } = require('pg'); //To communicate with the PostGreSQL Database
require('dotenv').config(); //To load environment variables from the .env file

module.exports.runQueryWithParams = (queryWithParams) => {
    return new Promise((resolve, reject) => {
        const client = new Client({
            connectionString: process.env.DATABASE_URL,
            ssl: true,
        });

        client.connect();

        client.query(queryWithParams.query, queryWithParams.params, (err, res) => {
            if (err) {
                console.log(err);
                reject(err);
            }
            resolve(res);
            client.end();
        });
    });
}

module.exports.runSimpleQuery = (query) => {
    return new Promise((resolve, reject) => {
        const client = new Client({
            connectionString: process.env.DATABASE_URL,
            ssl: true,
        });

        client.connect();

        client.query(query, [], (err, res) => {
            if (err) {
                console.log(err);
                reject(err);
            }
            resolve(res);
            client.end();
        });
    });
}

/*
CREATE TABLE USERS (
    USER_ID INT GENERATED BY DEFAULT AS IDENTITY,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    REGISTRATION_STATUS VARCHAR(10) NOT NULL,
    REGISTRATION_KEY VARCHAR(100) NOT NULL,
    REGISTRATION_START_DATE TIMESTAMP NOT NULL,
    REGISTRATION_COMPLETE_DATE TIMESTAMP,
    USER_TYPE VARCHAR(100) NOT NULL,
    PRIMARY KEY(USER_ID)
);

CREATE TABLE NOTES (
    NOTE_ID INT GENERATED BY DEFAULT AS IDENTITY,
    USER_ID INT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    NOTE VARCHAR(10485760),
    TAGS VARCHAR(10485760),
    ARCHIVED BOOLEAN NOT NULL,
    PINNED BOOLEAN NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    MODIFIED_DATE TIMESTAMP NOT NULL,
    IMAGE_TYPE VARCHAR(100),
    IMAGE_BASE_64 VARCHAR(10485760),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
  );

  CREATE TABLE PASSWORD_RESETS (
    USER_ID INT,
    NEW_PASSWORD VARCHAR(200) NOT NULL,
    RESET_KEY VARCHAR(100) NOT NULL,
    PRIMARY KEY (USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

Note:
 - Valid user types are REGULAR and ADMIN, and users must be changed to ADMIN manually (no in-app way to do so)
 - Valid registration statuses are PENDING and COMPLETE
*/